spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/hello
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        ddl-auto: create # update
        use_sql_comments: true
    show-sql: true
    generate-ddl: true
    open-in-view: false
logging:
  level:
    org.hibernate:
      type:
        descriptor.sql: trace